// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyUSoevsAR',
    appId: '1:561522285489:web:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '561522285489',
    projectId: 'easynema',
    authDomain: 'easynema.firebaseapp.com',
    storageBucket: 'easynema.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-QVQ8iuw7BAXJCFkxZDnUV8GNyQDh9U',
    appId: '1:561522285489:android:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '561522285489',
    projectId: 'easynema',
    storageBucket: 'easynema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nuP0Rjyts',
    appId: '1:561522285489:ios:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '561522285489',
    projectId: 'easynema',
    storageBucket: 'easynema.appspot.com',
    iosClientId:
        '561522285489-28moq8t1q24jf0no7icg38gao5kvrllp.apps.googleusercontent.com',
    iosBundleId: 'com.example.easynema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_nuP0Rjyts',
    appId: '1:561522285489:ios:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '561522285489',
    projectId: 'easynema',
    storageBucket: 'easynema.appspot.com',
    iosClientId:
        '561522285489-28moq8t1q24jf0no7icg38gao5kvrllp.apps.googleusercontent.com',
    iosBundleId: 'com.example.easynema',
  );
}
